server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # 路由id，自定义，只要唯一即可
          # url: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
#          filters:
#            - AddRequestHeader=Truth, 666 is freaking awesome! # 过滤器，增加一个请求头
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#            - After=2031-04-13T15:14:47.433+08:00[Asia/Shanghai] # 路径断言，判断是否在这个时间之后，如果是则符合
      default-filters:  # 默认过滤器，为全局配置
        - AddRequestHeader=Truth, 666 is freaking awesome! 1 # 过滤器的order值一样时，会按照defaultFilter > 路由过滤器 > GlobalFilter的顺序执行
#        - AxxxHeader=Truth, 666 is freaking awesome! 2
#        - AxxxHeader=Truth, 666 is freaking awesome! 3

