server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false&serverTimezone=UTC
    username: root
    password: klxsx123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        cluster-name: HangZhou # 集群名称

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

mybatis:
  type-aliases-package: com.chen.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

pattern:
  name: 本地环境local