server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false&serverTimezone=UTC
    username: root
    password: klxsx123
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice # order服务的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: HangZhou # 集群名称
#        namespace: 1e4ec190-89a3-40ee-86b8-85501d6bfcad # dev环境（环境隔离，不同环境下的服务不可见）
#        ephemeral: false # 设置为非临时服务，下线后不会被nacos剔除

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则

mybatis:
  type-aliases-package: com.chen.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.chen: debug
    com.alibaba.nacos.client.naming: WARN
    com.alibaba.nacos.client.config.impl: WARN
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients:
      - userservice

feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数